---
- name: "Preparing machine"
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensure python binary is present
      raw: "cd /usr/bin && sudo ln -sf python3 python"

- name: "Provision LAMPDeven machine"
  hosts: all
  vars_files:
    - vars/main.yml
  roles:
      - { role: Aplyca.WebApp, tags: ["webapp"] }
      - { role: Aplyca.S3fs, tags: ["s3fs"] }
      - { role: Aplyca.Cleanbox, tags: ["cleanbox"] }
